# Generated by Django 4.1.3 on 2022-11-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='spider',
            new_name='Spider',
        ),
    ]
