# Generated by Django 4.1.3 on 2022-11-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_spider_feeding_spider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='Spider',
            new_name='spider',
        ),
    ]
