# Generated by Django 4.1.3 on 2022-11-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_decoration_spider_decorations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('1', '🦗'), ('2', '🐛'), ('3', '🪲')], default='1', max_length=1),
        ),
    ]
